'use client';
import {useState,useEffect,useRef,useMemo} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Command,CommandInput,CommandList,CommandItem,CommandEmpty} from '@/components/ui/command';
import {Slider} from '@/components/ui/slider';
import {Progress} from '@/components/ui/progress';
import {Plus,Minus,Maximize,UserRound} from 'lucide-react';
import {layoutTree,photoURL} from '@/lib/layout.mjs';
import {name,dateText,uid} from '@/lib/model.mjs';
export function Choice({value,onChange,items,label}:{value:string,onChange:(s:string)=>void,items:[string,string][],label?:string}){return <Select dir="rtl" value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
export const views:[string,string][]=[['detail','מפורטת'],['vertical','שמות · לאורך'],['horizontal','שמות · לרוחב']];
export function Modal({title,description,open,onClose,children,wide=false}:any){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={'modal '+(wide?'wide':'')}><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription>{children}</DialogContent></Dialog>}
export function PersonPicker({people,value,onChange,label='חיפוש אדם קיים'}:any){return <div className="person-picker"><Command><CommandInput aria-label={label} placeholder={label}/><CommandList style={{maxHeight:180}}><CommandEmpty>לא נמצאו אנשים</CommandEmpty>{people.map((p:any)=><CommandItem key={p.id} value={name(p)+' '+p.id} onSelect={()=>onChange(p.id)}><span>{value===p.id?'✓ ':''}{name(p)} <small>· {p.id.slice(0,8)}</small></span></CommandItem>)}</CommandList></Command>{value&&<p className="muted">נבחר: {name(people.find((p:any)=>p.id===value)||{})}</p>}</div>}
export function TreeCanvas({tree,view,collapsed,onCollapse,onSelect,focus,fitToken=0,preview=false}:any){
 const layout=useMemo(()=>layoutTree(tree,view,collapsed),[tree,view,collapsed]);const ref=useRef<HTMLDivElement>(null);const [size,setSize]=useState({w:900,h:600});const [cam,setCam]=useState({x:0,y:0,z:1});const pointers=useRef(new Map<number,{x:number,y:number}>());const moved=useRef(false);
 useEffect(()=>{if(!ref.current)return;const o=new ResizeObserver(es=>{const r=es[0].contentRect;setSize({w:r.width,h:r.height})});o.observe(ref.current);return()=>o.disconnect()},[]);
 const fit=()=>{const z=Math.min(1.15,(size.w-48)/layout.width,(size.h-48)/layout.height);setCam({z,x:(size.w-layout.width*z)/2,y:(size.h-layout.height*z)/2})};
 useEffect(()=>{fit()},[layout,size,fitToken]);
 useEffect(()=>{if(!focus)return;const n=layout.nodes.find((n:any)=>n.id===focus.id);if(n)setCam({z:1,x:size.w/2-n.x-n.w/2,y:size.h/2-n.y-n.h/2})},[focus]);
 const zoom=(factor:number,x=size.w/2,y=size.h/2)=>setCam(c=>{const z=Math.min(3,Math.max(.001,c.z*factor));return{x:x-(x-c.x)*z/c.z,y:y-(y-c.y)*z/c.z,z}});
 const bounds={x:-cam.x/cam.z-250,y:-cam.y/cam.z-250,w:size.w/cam.z+500,h:size.h/cam.z+500};
 const nodes=layout.nodes.filter((n:any)=>n.x+n.w>=bounds.x&&n.x<=bounds.x+bounds.w&&n.y+n.h>=bounds.y&&n.y<=bounds.y+bounds.h);
 const edges=layout.edges.filter((e:any)=>e.maxX>=bounds.x&&e.minX<=bounds.x+bounds.w&&e.maxY>=bounds.y&&e.minY<=bounds.y+bounds.h);
 return <div className={'canvas '+(preview?'preview-tree':'')} ref={ref}><svg role="group" aria-label="אילן המשפחה. אפשר לבחור אדם לפתיחת פרטיו" width="100%" height="100%" style={{touchAction:'none'}} onWheel={e=>{e.preventDefault();const r=ref.current!.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.001),e.clientX-r.left,e.clientY-r.top)}} onPointerDown={e=>{moved.current=false;if((e.target as Element).closest(".person-node"))return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const old=pointers.current.get(e.pointerId);if(!old)return;const dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.abs(dx)+Math.abs(dy)>2)moved.current=true;if(pointers.current.size===2){const other=[...pointers.current.entries()].find(([id])=>id!==e.pointerId)![1];const before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(before>0){const r=ref.current!.getBoundingClientRect();zoom(after/before,(e.clientX+other.x)/2-r.left,(e.clientY+other.y)/2-r.top)}}else setCam(c=>({...c,x:c.x+dx,y:c.y+dy}));pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY})}} onPointerUp={e=>pointers.current.delete(e.pointerId)} onPointerCancel={()=>pointers.current.clear()}>
 <defs><clipPath id="person-photo"><circle cx="122" cy="38" r="25"/></clipPath></defs><g transform={`translate(${cam.x} ${cam.y}) scale(${cam.z})`}>
 {edges.map((e:any)=><polyline key={e.id+e.type} points={e.pts.map((p:any)=>p.join(',')).join(' ')} fill="none" stroke={e.type==='partner'?'#ad844b':'#83a0b2'} strokeWidth="1.8" strokeDasharray={e.type==='partner'?'6 4':undefined}/>)}
 {nodes.map((n:any)=>{const url=photoURL(n.p);const active=focus?.id===n.id;let y=view==='detail'?86:27;return <g key={n.id} transform={`translate(${n.x},${n.y})`} role="button" tabIndex={0} aria-label={name(n.p)} onClick={e=>{e.stopPropagation();if(!moved.current)onSelect?.(n.id)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(n.id)}}} className="person-node"><rect width={n.w} height={n.h} rx="11" fill={active?'#edf9fc':'#fff'} stroke={active?'#177e9a':'#c6d7e2'} strokeWidth={active?3:1.3}/><rect x={n.w-5} y="13" width="3" height={n.h-26} rx="1.5" fill="#43889a"/>
 {view==='detail'&&(url?<image href={url} x="96" y="12" width="52" height="52" preserveAspectRatio="xMidYMid slice" clipPath="url(#person-photo)"/>:<g><circle cx="122" cy="38" r="25" fill="#e7eff4"/><circle cx="122" cy="31" r="8" fill="#9bb3c1"/><path d="M105 55 Q105 41 122 41 Q139 41 139 55" fill="#9bb3c1"/></g>)}
 {n.lines.map((l:string,i:number)=><text key={i} x={n.w/2} y={y+i*24} textAnchor="middle" direction="rtl" fontSize="18" fontWeight="600" fill="#173e58">{l}</text>)}
 {view==='detail'&&<>{n.p.birthDate&&<text x={n.w/2} y={y+n.lines.length*24} textAnchor="middle" direction="rtl" fontSize="14" fill="#5c778a">לידה · {dateText(n.p.birthDate)}</text>}{n.p.deathDate&&<text x={n.w/2} y={y+n.lines.length*24+(n.p.birthDate?22:0)} textAnchor="middle" direction="rtl" fontSize="14" fill="#5c778a">פטירה · {dateText(n.p.deathDate)}</text>}</>}
 {!!n.p.childIds?.length&&!preview&&<g role="button" tabIndex={0} aria-label={collapsed.includes(n.id)?'הרחבת ענף':'כיווץ ענף'} transform={`translate(${n.w/2},${n.h})`} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onCollapse(n.id)}} onKeyDown={e=>{if(e.key==='Enter'){e.stopPropagation();onCollapse(n.id)}}}><circle r="11" fill="#173e58"/><text textAnchor="middle" y="5" fill="white" fontSize="16">{collapsed.includes(n.id)?'+':'−'}</text></g>}</g>})}</g></svg>
 {!preview&&<><div className="canvas-legend"><span><i/> הורות</span><span><i className="partner"/> זוגיות</span></div><div className="zoom-controls"><button aria-label="הגדלה" onClick={()=>zoom(1.25)}><Plus size={18}/></button><span>{Math.round(cam.z*100)}%</span><button aria-label="הקטנה" onClick={()=>zoom(.8)}><Minus size={18}/></button><button aria-label="התאם למסך" onClick={fit}><Maximize size={18}/></button></div></>}
 </div>
}
export function PhotoEditor({photo,onChange}:any){const [raw,setRaw]=useState<string|null>(null),[scale,setScale]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[err,setErr]=useState(''),[fileName,setFileName]=useState('photo.jpg');const preview=useRef<HTMLCanvasElement>(null),bitmap=useRef<ImageBitmap|null>(null);
 useEffect(()=>{const c=preview.current,b=bitmap.current;if(!c||!b)return;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,250,250);const side=Math.min(b.width,b.height)/scale;ctx.drawImage(b,(b.width-side)*x/100,(b.height-side)*y/100,side,side,0,0,250,250)},[raw,scale,x,y]);
 const load=async(f:File)=>{try{setErr('');if(!/^image\/(jpeg|png|webp)$/.test(f.type))throw Error('יש לבחור תמונת JPEG, PNG או WebP');bitmap.current?.close();bitmap.current=await createImageBitmap(f,{imageOrientation:'from-image'});setFileName(f.name);setScale(1);setX(50);setY(50);setRaw(f.name+Date.now())}catch(e:any){setErr(e.message)}};
 const save=()=>{const b=bitmap.current!;const c=document.createElement('canvas');c.width=c.height=900;const side=Math.min(b.width,b.height)/scale;c.getContext('2d')!.drawImage(b,(b.width-side)*x/100,(b.height-side)*y/100,side,side,0,0,900,900);onChange({id:uid(),mimeType:'image/jpeg',fileName:fileName.replace(/\.[^.]+$/,'.jpg'),data:c.toDataURL('image/jpeg',.94)});setRaw(null)};
 return <div className="photo-editor"><div className="photo-current">{photoURL({photo})?<img src={photoURL({photo})!} alt="תמונת האדם"/>:<UserRound size={36}/>}</div><div><label className="file-label">העלאת תמונה<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&load(e.target.files[0])}/></label>{photo&&<button type="button" className="text-button" onClick={()=>onChange(null)}>הסר תמונה</button>}</div>{err&&<p className="error">{err}</p>}<Modal open={!!raw} onClose={()=>setRaw(null)} title="חיתוך תמונה" description="התאימו את המסגרת ואת מרכז התמונה"><canvas ref={preview} width="250" height="250" className="crop-preview"/><label>הגדלה<Slider min={1} max={4} step={.05} value={[scale]} onValueChange={v=>setScale(v[0])}/></label><label>מיקום אופקי<Slider min={0} max={100} value={[x]} onValueChange={v=>setX(v[0])}/></label><label>מיקום אנכי<Slider min={0} max={100} value={[y]} onValueChange={v=>setY(v[0])}/></label><button className="primary" onClick={save}>השתמש בתמונה</button></Modal></div>
}
export function Busy({value,text}:{value:number,text:string}){return <div className="busy" role="status"><p>{text}</p><Progress value={value*100}/></div>}

