'use client';
import {useMemo,useState,useEffect} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {Modal,Choice,TreeCanvas,Busy,views} from './family-ui';
import {inspectImport,mergeTrees,uid,exportTree} from '@/lib/model.mjs';
import {exportJSON,png,renderPrintPages,pdfBlob,download,filename,singlePage,fullBackup} from '@/lib/exports.mjs';
export function ImportDialog({tree,open,onClose,onImport}:any){const [file,setFile]=useState<File|null>(null),[raw,setRaw]=useState<any>(null),[error,setError]=useState(''),[resolutions,setResolutions]=useState<any>({}),[choices,setChoices]=useState<any>({}),[mode,setMode]=useState('replace'),[busy,setBusy]=useState(false),[ack,setAck]=useState(false),[progress,setProgress]=useState(0);
 useEffect(()=>{if(open){setRaw(null);setFile(null);setError('');setAck(false);setChoices({});setResolutions({})}},[open]);
 const inspected=useMemo(()=>raw?inspectImport(raw,resolutions):null,[raw,resolutions]);const merged=useMemo(()=>inspected&&mode==='merge'?mergeTrees(tree,inspected.tree,choices):null,[tree,inspected,mode,choices]);
 const check=async()=>{setBusy(true);setError('');setProgress(.15);try{if(!file||!file.name.toLowerCase().endsWith('.json'))throw Error('יש לבחור קובץ עם סיומת .json בלבד');const content=await file.text();setProgress(.6);setResolutions({});setChoices({});setRaw(JSON.parse(content.replace(/^\uFEFF/,'')));setAck(false);setProgress(1)}catch(e:any){setRaw(null);setError(e instanceof SyntaxError?'הקובץ אינו JSON תקין. העץ הקיים לא השתנה; אפשר לבחור קובץ אחר.':e.message)}finally{setBusy(false)}};
 const apply=async()=>{setBusy(true);setError('');try{if(tree.persons.length){const backup=await fullBackup(tree,(p:number)=>setProgress(p*.5));download(new Blob([JSON.stringify(backup,null,2)],{type:'application/json;charset=utf-8'}),'backup-before-import-'+filename('json'))}let next=merged?.tree||inspected!.tree;next={...next,metadata:{...next.metadata,importedAt:new Date().toISOString(),reviewAcknowledged:ack}};await onImport(next);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const hasIssues=!!(inspected?.warnings.length||inspected?.tree.reviewItems.length);
 return <Modal wide open={open} onClose={onClose} title="ייבוא קובץ JSON" description="בדקו את הקובץ, פתרו סתירות ואשרו את הייבוא. העץ הקיים יישאר ללא שינוי עד לאישור."><label>קובץ עץ משפחתי<input type="file" accept=".json,application/json" onChange={e=>{setFile(e.target.files?.[0]||null);setRaw(null);setError('')}}/></label><button disabled={!file||busy} onClick={check} className="primary">בדוק קובץ</button>{busy&&<Busy value={progress} text="בודק ומכין את הנתונים…"/>}{error&&<p role="alert" className="error">{error}</p>}
 {inspected&&<><div className="stats-row"><strong>{inspected.stats?.persons||0} אנשים</strong><span>{inspected.stats?.families||0} יחידות משפחתיות</span><span>{inspected.stats?.relationships||0} קשרי הורות</span></div>{inspected.errors.map((s:string,i:number)=><p className="error" key={i}>{s}</p>)}
 {inspected.allConflicts?.map((c:any)=><div className="conflict" key={c.id}><p>{c.label}</p><Choice label="פתרון הסתירה" value={resolutions[c.id]||'pending'} onChange={v=>setResolutions({...resolutions,[c.id]:v})} items={([['pending','בחרו פתרון מפורש'],...c.choices.map((v:string)=>[v,({include:'כלול את הקשר',exclude:'אל תכלול את הקשר',retain:'שמור קשר והסר שיוך סותר',detach:'נתק מהיחידה המשפחתית'} as any)[v]||v])]) as any}/></div>)}
 {!inspected.errors.length&&<TreeCanvas tree={inspected.tree} view="vertical" collapsed={[]} preview/>}
 {inspected.warnings.map((s:string,i:number)=><p className="notice" key={i}>{s}</p>)}
 {!!inspected.tree.reviewItems.length&&<details open><summary>פרטים לבדיקה · {inspected.tree.reviewItems.length}</summary>{inspected.tree.reviewItems.map((r:any,i:number)=><pre key={i}>{JSON.stringify(r,null,2)}</pre>)}</details>}
 {!!inspected.tree.confirmations.length&&<details><summary>אישורים קיימים · {inspected.tree.confirmations.length}</summary><pre>{JSON.stringify(inspected.tree.confirmations,null,2)}</pre></details>}
 {tree.persons.length>0&&<><label>אופן הייבוא<Choice value={mode} onChange={setMode} items={[["replace","החלפה מלאה — עם גיבוי לפני החלפה"],["merge","מיזוג לפי מזהים"]]}/></label>{mode==='merge'&&<p className="muted">העץ הקיים מכיל {tree.persons.length} אנשים; לאחר המיזוג: {merged?.tree.persons.length}. בחירה בשינוי מזהה מעדכנת גם את ההפניות המוכרות בקובץ המיובא.</p>}{merged?.conflicts.map((c:any)=><div className="conflict" key={c.id}><strong>{c.label}</strong><div className="two-cols"><pre>{JSON.stringify(c.existing,null,2)}</pre><pre>{JSON.stringify(c.incoming,null,2)}</pre></div><div className="actions"><button onClick={()=>setChoices({...choices,[c.id]:'existing'})}>שמור קיים</button><button onClick={()=>setChoices({...choices,[c.id]:'incoming'})}>השתמש במיובא</button>{c.collection==='persons'&&<button onClick={()=>setChoices({...choices,[c.id]:'rename:'+uid()})}>אלו אנשים שונים · צור מזהה חדש למיובא</button>}</div></div>)}{merged?.allRelationshipConflicts?.map((c:any)=><div className="conflict" key={c.id}><p>{c.label}</p><Choice label="פתרון סתירת קשר במיזוג" value={choices[c.id]||'pending'} onChange={v=>setChoices({...choices,[c.id]:v})} items={([['pending','בחרו פתרון מפורש'],...c.choices.map((v:string)=>[v,({include:'כלול את הקשר',exclude:'אל תכלול את הקשר',detach:'שמור את ההורות ללא שיוך ליחידה הסותרת'} as any)[v]||v])]) as any}/></div>)}{merged?.errors.map((s:string,i:number)=><p className="error" key={i}>{s}</p>)}</>}
 {hasIssues&&<label className="check-line"><Checkbox checked={ack} onCheckedChange={v=>setAck(v===true)}/> קראתי את הפרטים לבדיקה. הם יישארו לא ודאיים לאחר הייבוא.</label>}
 <p className="muted">החלפה ומיזוג הם פעולה שלמה. לפני שינוי עץ קיים יורד גיבוי מלא, כולל תמונות.</p><button className="primary" disabled={busy||!!inspected.errors.length||!!inspected.conflicts.length||!!merged?.conflicts.length||!!merged?.errors.length||!!merged?.relationshipConflicts.length||hasIssues&&!ack} onClick={apply}>אשר ייבוא</button></>}
 </Modal>
}
export function ExportDialog({tree,open,onClose}:any){const [view,setView]=useState('detail'),[mode,setMode]=useState('single'),[orientation,setOrientation]=useState('auto'),[resolution,setResolution]=useState('2'),[background,setBackground]=useState('white'),[full,setFull]=useState('full'),[previews,setPreviews]=useState<any[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');
 useEffect(()=>{setPreviews([]);setError('')},[tree,view,mode,orientation]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setProgress(0);try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const preview=()=>run(async()=>{const p=await renderPrintPages(tree,view,mode,orientation,.65,setProgress);setPreviews(p.map((q:any)=>({url:q.canvas.toDataURL('image/png'),width:q.width,height:q.height}))) });
 const pdf=(print=false)=>run(async()=>{const p=await renderPrintPages(tree,view,mode,orientation,2.5,setProgress);const blob=pdfBlob(p);if(print){const u=URL.createObjectURL(blob);const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:1px;height:1px;left:-1000px';frame.src=u;frame.onload=()=>{setTimeout(()=>{try{frame.contentWindow?.focus();frame.contentWindow?.print()}catch{download(blob,filename('pdf'))}},600)};document.body.appendChild(frame);setTimeout(()=>{frame.remove();URL.revokeObjectURL(u)},180000)}else download(blob,filename('pdf'))});
 const single=useMemo(()=>singlePage(tree,view,orientation),[tree,view,orientation]);
 return <Modal wide open={open} onClose={onClose} title="ייצוא והדפסה" description="הייצוא כולל את כל העץ, גם אנשים מחוץ למסך וענפים מכווצים."><div className="two-cols"><label>תצוגה<Choice value={view} onChange={setView} items={views}/></label><label>פריסת הדפסה<Choice value={mode} onChange={setMode} items={[["single","כל העץ על A4 אחד"],["multi","רוחב A4 · מספר עמודים לפי הצורך"]]}/></label><label>כיוון הדף<Choice value={orientation} onChange={setOrientation} items={[["auto","אוטומטי"],["portrait","לאורך"],["landscape","לרוחב"]]}/></label><label>רזולוציית PNG<Choice value={resolution} onChange={setResolution} items={[["1","רגילה ×1"],["2","גבוהה ×2"],["3","להדפסה ×3"]]}/></label><label>רקע PNG<Choice value={background} onChange={setBackground} items={[["white","לבן"],["transparent","שקוף"]]}/></label></div>
 {mode==='single'&&<p className={single.fontPt<7?'notice':'muted'}>גודל השם המשוער בהדפסה: {single.fontPt.toFixed(1)} נקודות. {single.fontPt<7?'הטקסט קטן מאוד. מומלץ לבחור שמות בלבד או מספר עמודים. עדיין אפשר להפיק את כל העץ בדף אחד.':''}</p>}
 {mode==='multi'&&<p className="notice">הפריסה אנכית, ברוחב עמוד אחד. מזהי P בכרטיסים ומפתח הקשרים בסוף הקובץ מקשרים בין הענפים ומפנים לעמודים הרלוונטיים.</p>}
 <div className="actions"><button disabled={busy||!tree.persons.length} onClick={preview}>תצוגה מקדימה לכל העמודים</button><button disabled={busy||!tree.persons.length} onClick={()=>pdf()} className="primary">הורדת PDF</button><button disabled={busy||!tree.persons.length} onClick={()=>pdf(true)}>הדפסה</button><button disabled={busy||!tree.persons.length} onClick={()=>run(async()=>{await png(tree,view,Number(resolution),background==='white',setProgress)})}>הורדת PNG מלא</button></div>
 {busy&&<Busy value={progress} text={`מכין ייצוא · ${Math.round(progress*100)}%`}/>} {error&&<p role="alert" className="error">{error}</p>}<div className="print-preview">{previews.map((p,i)=><figure key={i}><img src={p.url} alt={`תצוגה מקדימה של עמוד ${i+1}`} /><figcaption>עמוד {i+1} מתוך {previews.length}</figcaption></figure>)}</div>
 <div className="export-json"><h3>גיבוי נתוני המשפחה</h3><label>תוכן קובץ JSON<Choice value={full} onChange={setFull} items={[["full","גיבוי מלא · כולל תוכן התמונות"],["data","נתונים בלבד · ללא קובצי התמונות"]]}/></label><p className="muted">{full==='data'?'קובצי התמונות אינם כלולים. הקובץ מכיל הפניות בלבד.':'כל נתוני העץ והתמונות נשמרים בקובץ JSON יחיד, שאפשר לייבא מחדש.'}</p><button disabled={busy} onClick={()=>run(async()=>{await exportJSON(tree,full==='full',setProgress)})}>ייצוא נתוני העץ ל־JSON</button></div></Modal>
}

