import {layoutTree,printPages,photoURL} from './layout.mjs';
import {dateText,exportTree} from './model.mjs';
export const download=(blob,file)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=file;a.textContent='הקובץ מוכן: '+file;a.className='download-ready';a.style.cssText='display:block;padding:12px;overflow-wrap:anywhere;color:#246276';(document.querySelector('[role=dialog]')||document.body).appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(u)},180000)};
export const filename=ext=>`yehuda-family-tree-${new Date().toISOString().slice(0,10)}.${ext}`;
export async function fullBackup(tree,onProgress=(_value)=>{}){const t=exportTree(tree,true);let i=0;for(const p of t.persons){const u=photoURL(p);if(u&&!u.startsWith('data:')){const r=await fetch(u);if(!r.ok)throw Error(`לא ניתן לכלול את התמונה של ${p.fullName}. הגיבוי לא הופק.`);const b=await r.blob();const data=await new Promise((ok,no)=>{const f=new FileReader();f.onload=()=>ok(f.result);f.onerror=no;f.readAsDataURL(b)});p.photo={...(typeof p.photo==='object'?p.photo:{}),id:p.photo?.id||p.id+'-photo',mimeType:b.type,fileName:p.photo?.fileName||'photo.jpg',data}}onProgress(++i/t.persons.length)}return t}
export async function exportJSON(tree,full=false,onProgress){const t=full?await fullBackup(tree,onProgress):exportTree(tree,false);download(new Blob([JSON.stringify(t,null,2)],{type:'application/json;charset=utf-8'}),filename('json'));return t}
const img=src=>new Promise((ok,no)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>ok(i);i.onerror=()=>no(Error('לא ניתן לטעון תמונה לייצוא. יש להעלות אותה מחדש לאתר.'));i.src=src});
export async function loadPhotos(tree,progress=(_value)=>{}){const images=new Map();const people=tree.persons.filter(p=>photoURL(p));let i=0;for(const p of people){images.set(p.id,await img(photoURL(p)));progress(++i/people.length)}return images}
export function paintNode(ctx,n,view,images){
 ctx.save();ctx.translate(n.x,n.y);if(n.scale)ctx.scale(n.scale,n.scale);const w=n.w/(n.scale||1),h=n.h/(n.scale||1);
 ctx.fillStyle='#fff';ctx.strokeStyle='#b9cedb';ctx.lineWidth=1.2;ctx.beginPath();ctx.roundRect(0,0,w,h,10);ctx.fill();ctx.stroke();ctx.fillStyle='#327f94';ctx.fillRect(w-5,12,3,h-24);
 ctx.direction='rtl';ctx.textAlign='center';ctx.textBaseline='middle';let y=22;
 if(view==='detail'){const im=images?.get(n.id);const cx=w/2;ctx.save();ctx.beginPath();ctx.arc(cx,38,25,0,Math.PI*2);ctx.clip();ctx.fillStyle='#e6eff4';ctx.fillRect(cx-26,12,52,52);if(im){const s=Math.max(52/im.width,52/im.height);ctx.drawImage(im,cx-im.width*s/2,38-im.height*s/2,im.width*s,im.height*s)}else{ctx.fillStyle='#9eb7c6';ctx.beginPath();ctx.arc(cx,30,9,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(cx,57,18,16,0,0,Math.PI*2);ctx.fill()}ctx.restore();y=86}
 ctx.fillStyle='#153b53';ctx.font='600 18px Arial';for(const l of n.lines){ctx.fillText(l,w/2,y);y+=24}
 if(view==='detail'){ctx.font='14px Arial';ctx.fillStyle='#526f82';if(n.p.birthDate){ctx.fillText('לידה · '+dateText(n.p.birthDate),w/2,y);y+=22}if(n.p.deathDate){ctx.fillText('פטירה · '+dateText(n.p.deathDate),w/2,y);y+=22}}
 if(n.marker){ctx.font='12px Arial';ctx.fillStyle='#647c89';ctx.fillText(n.continuation||n.marker,w/2,h-17)}ctx.restore();
}
export function paint(ctx,layout,images){for(const e of layout.edges){ctx.save();ctx.strokeStyle=e.type==='partner'?'#aa8043':'#789bae';ctx.lineWidth=1.7;ctx.setLineDash(e.type==='partner'?[6,4]:[]);ctx.beginPath();e.pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();ctx.restore()}for(const n of layout.nodes)paintNode(ctx,n,layout.view,images)}
export function makeCanvas(w,h,scale=1,white=true){const width=Math.ceil(w*scale),height=Math.ceil(h*scale);if(width>16384||height>16384||width*height>40000000)throw Error('התמונה חורגת ממגבלת הזיכרון הבטוחה (40 מיליון פיקסלים או 16,384 פיקסלים בצלע). יש להפחית רזולוציה או לבחור PDF מרובה עמודים. לא הופק קובץ חלקי.');const c=document.createElement('canvas');c.width=width;c.height=height;const ctx=c.getContext('2d');if(!ctx)throw Error('הדפדפן אינו תומך בייצוא תמונה');if(white){ctx.fillStyle='white';ctx.fillRect(0,0,width,height)}ctx.scale(scale,scale);return {c,ctx}}
export async function png(tree,view,scale=2,white=true,progress=(_value)=>{}){progress(.05);const l=layoutTree(tree,view);const images=view==='detail'?await loadPhotos(tree,p=>progress(.05+p*.45)):new Map();const {c,ctx}=makeCanvas(l.width,l.height,scale,white);paint(ctx,l,images);progress(.85);const blob=await new Promise(ok=>c.toBlob(ok,'image/png'));if(!blob)throw Error('הדפדפן לא הצליח ליצור תמונה בגודל זה. יש להפחית רזולוציה.');download(blob,filename('png'));progress(1);return {width:c.width,height:c.height}}
export function singlePage(tree,view,orientation='auto'){const l=layoutTree(tree,view);const opts=[{width:794,height:1123,label:'portrait'},{width:1123,height:794,label:'landscape'}].map(p=>({...p,scale:Math.min((p.width-64)/l.width,(p.height-100)/l.height)}));const p=orientation==='auto'?opts.sort((a,b)=>b.scale-a.scale)[0]:opts.find(p=>p.label===orientation);return {...p,layout:l,fontPt:18*p.scale*.75}}
export async function renderPrintPages(tree,view,mode,orientation,scale=1,progress=(_value)=>{}){
 const images=view==='detail'?await loadPhotos(tree,p=>progress(p*.2)):new Map();const pages=mode==='single'?[singlePage(tree,view,orientation)]:printPages(tree,view,orientation==='landscape'?'landscape':'portrait');const results=[];
 for(let i=0;i<pages.length;i++){const p=pages[i];const {c,ctx}=makeCanvas(p.width,p.height,scale,true);ctx.direction='rtl';ctx.textAlign='center';ctx.fillStyle='#173e58';ctx.font='16px Arial';ctx.fillText('אילן היוחסין של משפחת יהודה',p.width/2,32);if(mode==='single'){ctx.save();ctx.translate((p.width-p.layout.width*p.scale)/2,55+(p.height-100-p.layout.height*p.scale)/2);ctx.scale(p.scale,p.scale);paint(ctx,p.layout,images);ctx.restore()}else if(p.kind==='tree')paint(ctx,p,images);else{ctx.font='bold 19px Arial';ctx.fillText('מפתח קשרים והמשכי ענפים',p.width/2,70);ctx.font='15px Arial';ctx.textAlign='right';for(const r of p.links)r.lines.forEach((s,j)=>ctx.fillText(s,p.width-44,r.y+j*22))}ctx.font='12px Arial';ctx.textAlign='center';ctx.fillStyle='#6f818d';ctx.direction='ltr';ctx.fillText(`${i+1} / ${pages.length}`,p.width/2,p.height-22);if(scale>1){results.push({jpeg:c.toDataURL('image/jpeg',.96),pixelWidth:c.width,pixelHeight:c.height,width:p.width,height:p.height});c.width=1;c.height=1}else results.push({canvas:c,width:p.width,height:p.height});progress(.2+.8*(i+1)/pages.length);await new Promise(r=>setTimeout(r,0))}return results;
}
// Minimal PDF 1.4 encoder: each A4 page embeds its own high-resolution JPEG.
// Hebrew is shaped by the browser canvas, independent of PDF viewer font support.
export function pdfBlob(pages){const enc=new TextEncoder(),parts=[],offsets=[0];let bytes=0;const push=b=>{const a=typeof b==='string'?enc.encode(b):b;parts.push(a);bytes+=a.length};push('%PDF-1.4\n');let next=3;const objects=[];const kids=[];
 for(const p of pages){const id=next;next+=3;kids.push(id);const u=(p.jpeg||p.canvas.toDataURL('image/jpeg',.96)).split(',')[1],raw=Uint8Array.from(atob(u),c=>c.charCodeAt(0)),w=(p.width>p.height?297:210)/25.4*72,h=(p.width>p.height?210:297)/25.4*72,content=`q ${w} 0 0 ${h} 0 0 cm /Im Do Q`;objects.push([id,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${w} ${h}] /Resources << /XObject << /Im ${id+1} 0 R >> >> /Contents ${id+2} 0 R >>`]);objects.push([id+1,[`<< /Type /XObject /Subtype /Image /Width ${p.pixelWidth||p.canvas.width} /Height ${p.pixelHeight||p.canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${raw.length} >>\nstream\n`,raw,'\nendstream']]);objects.push([id+2,`<< /Length ${content.length} >>\nstream\n${content}\nendstream`])}
 objects.unshift([1,'<< /Type /Catalog /Pages 2 0 R >>'],[2,`<< /Type /Pages /Count ${pages.length} /Kids [${kids.map(x=>`${x} 0 R`).join(' ')}] >>`]);for(const [id,body]of objects){offsets[id]=bytes;push(`${id} 0 obj\n`);if(Array.isArray(body))body.forEach(push);else push(body);push('\nendobj\n')}const start=bytes;push(`xref\n0 ${next}\n0000000000 65535 f \n`);for(let i=1;i<next;i++)push(`${String(offsets[i]).padStart(10,'0')} 00000 n \n`);push(`trailer\n<< /Size ${next} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`);return new Blob(parts,{type:'application/pdf'})}

